### ISSUE TITLE
Time format issue in parse_ebm_record

### ISSUE THREAD

**Issue by Steph-Fulda** [bwrc/embla-r#3]
Hi there,

thanks for the great embla-r funtions which I have been trying out. While doing so I noticed that there is a formatting error /typo for the extracted starting time in the parse_ebm_record, line 124
"%d%02d%02dT%02d%02d## **%0d2**.%02d" which results in considerable time shifts of the signal in particular compared to any extracted annotation.
With kind regards
Steph

**Comment by aheneliu** [comment]
Fixed. Now this reads
`sprintf("%d%02d%02dT%02d%02d%02d.%02d", year, month, day, hour, minute, second, sec100)`
