### ISSUE TITLE
Issue with joining > 2 parts of recording

### ISSUE THREAD

**Issue by Steph-Fulda** [bwrc/embla-r#4]
Hi again,

just wanted to let you know that there was another issue, when the recording signal has more than 2 starts, in read_ebm lines 278-282, where i and i+1 should be 2_(i-1) and 2_(i-1) + 1

```
        ## create filler time and data vector
        time_vector[[2*(i-1)]] <- seq.int(from = t_stop[[i - 1]], to = t_start[[i]], by = (1 / header$EBM_R_SAMPLING_RATE))
        data_vector[[2*(i-1)]] <- rep(NA, length(time_vector[[2*(i-1)]]))

        time_vector[[2*(i-1) + 1]] <- t_start[[i]] + seq.int(0, (length(signal[[i]]) - 1)) / header$EBM_R_SAMPLING_RATE
        data_vector[[2*(i-1) + 1]] <- signal[[i]]
```

in the current case a a recording with 3 starts, the second part will be missing etc.

Cheers, steph

**Comment by aheneliu** [comment]
Thanks!
This should also be fixed now.
